export type Station = {
    name: string;
    city: string;
    genre: string;
    url: string;
};

export const radioData: Record<string, Station[]> = {
    "Argentina": [
        { name: "Radio Mitre", city: "Buenos Aires", genre: "News/Talk", url: "http://192.240.102.133:11306/stream" },
        { name: "La 100", city: "Buenos Aires", genre: "Top 40", url: "http://192.240.102.133:11322/stream" },
        { name: "Aspen 102.3", city: "Buenos Aires", genre: "Classic Hits", url: "http://192.240.102.133:11330/stream" },
        { name: "Rock & Pop 95.9", city: "Buenos Aires", genre: "Rock", url: "http://192.240.102.133:11962/stream" },
        { name: "Radio Continental", city: "Buenos Aires", genre: "News/Talk", url: "http://streaming.continental.com.ar:8000/Continental_Corrientes" },
        { name: "Los 40 Argentina", city: "Buenos Aires", genre: "Pop", url: "http://192.240.102.133:11314/stream" },
        { name: "Metro 95.1", city: "Buenos Aires", genre: "Pop/Electronic", url: "https://stream.metro951.com/metro951" },
        { name: "Radio Rivadavia", city: "Buenos Aires", genre: "News/Talk", url: "http://192.240.102.133:10998/stream" },
        { name: "Blue 100.7", city: "Buenos Aires", genre: "Chillout/Electronic", url: "https://live.bluefm.com.ar/blue/mp3/icecast.audio" },
        { name: "Vorterix", city: "Buenos Aires", genre: "Rock", url: "https://vorterix.radiocut.fm/listen" },
        { name: "Radio Nacional", city: "Buenos Aires", genre: "Public", url: "http://190.105.176.3:8000/radionacional" },
        { name: "Urbana Play FM", city: "Buenos Aires", genre: "Talk/Music", url: "https://streaming.urbanaplayfm.com/metro" },
        { name: "Radio Disney", city: "Buenos Aires", genre: "Pop", url: "https://radioradio.es/wp-content/plugins/player-radio/repro.php?url=http://192.240.102.133:11890/stream" },
        { name: "Cadena 3", city: "Córdoba", genre: "General", url: "http://190.105.176.3:8000/cadena3" },
        { name: "FM Milenium", city: "Buenos Aires", genre: "Adult Contemporary", url: "http://sa.mp3.icecast.magma.edge-access.net:7200/sc_rad105" },
        { name: "Radio con Vos", city: "Buenos Aires", genre: "Talk", url: "https://radioconvos.radiocut.fm/listen" },
        { name: "FM Tango", city: "Buenos Aires", genre: "Tango", url: "http://stream.e-radio.com.py:8000/fmtango" },
        { name: "Nacional Rock", city: "Buenos Aires", genre: "Rock", url: "http://190.105.176.3:8000/nacionalrock" },
        { name: "Radio La Red", city: "Buenos Aires", genre: "Sports", url: "http://192.240.102.133:12002/stream" },
        { name: "Futurock FM", city: "Buenos Aires", genre: "Independent", url: "https://futurock.radiocut.fm/listen" }
    ],
    "Australia": [
        { name: "Triple J", city: "Sydney", genre: "Alternative", url: "https://ic6.mainstreamnetwork.com/triplej-128.mp3" },
        { name: "Double J", city: "Sydney", genre: "Nostalgic Alt", url: "http://live-radio01.mediahubaustralia.com/3DBL/mp3/" },
        { name: "ABC Classic", city: "Sydney", genre: "Classical", url: "http://live-radio01.mediahubaustralia.com/3ABCFM/mp3/" },
        { name: "ABC RN", city: "Sydney", genre: "Talk/News", url: "https://ic6.mainstreamnetwork.com/abcrn-128.mp3" },
        { name: "PBS 106.7FM", city: "Melbourne", genre: "Community/Specialist", url: "https://playerservices.streamtheworld.com/api/livestream-redirect/PBSFM_ADP.m3u8" },
        { name: "RRR 102.7FM", city: "Melbourne", genre: "Community/Music", url: "http://real.rrr.org.au:8000/128" },
        { name: "FBi Radio 94.5", city: "Sydney", genre: "Local Music/Arts", url: "http://stream.fbiradio.com:8000/stream.mp3" },
        { name: "4ZZZ", city: "Brisbane", genre: "Community", url: "http://stream.4zzz.org.au:8000/4zzz" },
        { name: "2SER 107.3", city: "Sydney", genre: "Community", url: "https://playerservices.streamtheworld.com/api/livestream-redirect/2SERAAC.aac" },
        { name: "RTRFM 92.1", city: "Perth", genre: "Community/Music", url: "http://live-stream.rtrfm.com.au:8000/stream" },
        { name: "SmoothFM 95.3", city: "Sydney", genre: "Easy Listening", url: "https://playerservices.streamtheworld.com/api/livestream-redirect/SMOOTHFM_SC" },
        { name: "Nova 96.9", city: "Sydney", genre: "Top 40", url: "https://playerservices.streamtheworld.com/api/livestream-redirect/NOVA969_SC" },
        { name: "KIIS 106.5", city: "Sydney", genre: "Top 40", url: "https://playerservices.streamtheworld.com/api/livestream-redirect/KIIS1065_SC" },
        { name: "Gold 104.3", city: "Melbourne", genre: "Classic Hits", url: "https://playerservices.streamtheworld.com/api/livestream-redirect/GOLD1043_SC" },
        { name: "SEN 1116", city: "Melbourne", genre: "Sports", url: "https://playerservices.streamtheworld.com/api/livestream-redirect/SEN1116.mp3" },
        { name: "ABC Jazz", city: "National", genre: "Jazz", url: "http://live-radio01.mediahubaustralia.com/3JAZ/mp3/" },
        { name: "ABC Country", city: "National", genre: "Country", url: "http://live-radio01.mediahubaustralia.com/3ABCR/mp3/" },
        { name: "KIIS 101.1", city: "Melbourne", genre: "Top 40", url: "https://playerservices.streamtheworld.com/api/livestream-redirect/KIIS1011.mp3" },
        { name: "CADA 96.1", city: "Sydney", genre: "Hip Hop/RnB", url: "https://playerservices.streamtheworld.com/api/livestream-redirect/CADA.mp3" },
        { name: "3AW", city: "Melbourne", genre: "News/Talk", url: "https://stream.3aw.com.au/3aw" }
    ],
    "Brazil": [
        { name: "Antena 1", city: "São Paulo", genre: "Lite Adult Contemporary", url: "http://antena1.newradio.it/stream" },
        { name: "Rádio Gaúcha", city: "Porto Alegre", genre: "News/Talk/Sports", url: "https://playerservices.streamtheworld.com/api/livestream-redirect/RGAUCHA.mp3" },
        { name: "CBN", city: "São Paulo", genre: "News/Talk", url: "https://playerservices.streamtheworld.com/api/livestream-redirect/CBNSP.mp3" },
        { name: "Kiss FM", city: "São Paulo", genre: "Classic Rock", url: "https://playerservices.streamtheworld.com/api/livestream-redirect/KISSFM.mp3" },
        { name: "89 FM A Rádio Rock", city: "São Paulo", genre: "Rock", url: "https://playerservices.streamtheworld.com/api/livestream-redirect/RADioroCK.mp3" },
        { name: "BandNews FM", city: "São Paulo", genre: "News", url: "https://playerservices.streamtheworld.com/api/livestream-redirect/BANDNEWS_SP.mp3" },
        { name: "Alpha FM", city: "São Paulo", genre: "Adult Contemporary", url: "http://players.alphastream.com.br:80/alpha-hd" },
        { name: "Bossa Nova Brazil", city: "Online", genre: "Bossa Nova", url: "https://centova.radios.com.br/proxy/834?mp=/stream" },
        { name: "Radio Cidade", city: "Rio de Janeiro", genre: "Rock", url: "https://playerservices.streamtheworld.com/api/livestream-redirect/RADIOCIDADE_RJ.mp3" },
        { name: "Transamérica Pop", city: "São Paulo", genre: "Pop", url: "https://playerservices.streamtheworld.com/api/livestream-redirect/TRASP_SP.mp3" },
        { name: "Nativa FM", city: "São Paulo", genre: "Sertanejo", url: "https://playerservices.streamtheworld.com/api/livestream-redirect/NATIVAFMSP.mp3" },
        { name: "Mundo Livre FM", city: "Curitiba", genre: "Alternative", url: "https://playerservices.streamtheworld.com/api/livestream-redirect/MUNDOLIVRE.mp3" },
        { name: "Rádio Itapema", city: "Florianópolis", genre: "Adult Alternative", url: "https://playerservices.streamtheworld.com/api/livestream-redirect/ITAPEMAFMFLN.mp3" },
        { name: "Choro Brazil", city: "Online", genre: "Choro", url: "http://stream.choro.live:8000/stream" },
        { name: "Jovem Pan FM", city: "São Paulo", genre: "Pop/Talk", url: "https://playerservices.streamtheworld.com/api/livestream-redirect/JP_SP_FM.mp3" },
        { name: "Rádio Mix FM", city: "São Paulo", genre: "Pop", url: "https://playerservices.streamtheworld.com/api/livestream-redirect/MIXFM_SP.mp3" },
        { name: "Rádio Melodia", city: "Rio de Janeiro", genre: "Gospel", url: "https://playerservices.streamtheworld.com/api/livestream-redirect/RDMELODIA.mp3" },
        { name: "JB FM", city: "Rio de Janeiro", genre: "Adult Contemporary", url: "https://playerservices.streamtheworld.com/api/livestream-redirect/JBFM.mp3" },
        { name: "Energia 97", city: "São Paulo", genre: "Electronic Dance", url: "https://energia.api.stm.streamingmedia.com.br/player-fm/remote/;" },
        { name: "Dum-Dum FM", city: "Online", genre: "Hip Hop", url: "https://servidor31.brlogic.com:8132/live" }
    ],
    "Canada": [
        { name: "CBC Radio One", city: "Toronto", genre: "News/Talk", url: "http://cbc_r1_tor.akacast.akamaistream.net/7/632/451661/v1/rc.akacast.akamaistream.net/cbc_r1_tor" },
        { name: "CBC Music", city: "Toronto", genre: "Eclectic", url: "http://cbc_r2_tor.akacast.akamaistream.net/7/364/451661/v1/rc.akacast.akamaistream.net/cbc_r2_tor" },
        { name: "Indie88", city: "Toronto", genre: "Indie Rock", url: "http://icecast.indie88.com/indie88" },
        { name: "Jazz FM91", city: "Toronto", genre: "Jazz", url: "http://jazzfm91.streamb.live/SB00009" },
        { name: "CHOM 97.7", city: "Montreal", genre: "Rock", url: "https://rfcmedia.streamon.fm/chom" },
        { name: "Boom 97.3", city: "Toronto", genre: "70s/80s/90s", url: "http://boom973.akacast.akamaistream.net/7/850/177421/v1/astral.akacast.akamaistream.net/boom973" },
        { name: "The Edge 102.1", city: "Toronto", genre: "Alternative Rock", url: "https://edge.streamon.fm/CFNY-48k.aac" },
        { name: "Classical 96.3 FM", city: "Toronto", genre: "Classical", url: "http://classical963.streamon.fm:8000/CFMZ-48k.aac" },
        { name: "CKUA", city: "Edmonton", genre: "Eclectic", url: "http://ckualive.stream.kualabs.com/ckua_lq.mp3" },
        { name: "CJSW 90.9", city: "Calgary", genre: "College Radio", url: "http://stream.cjsw.com/cjsw.mp3" },
        { name: "CIUT-FM", city: "Toronto", genre: "Community/Variety", url: "http://s2.voscast.com:8026/;" },
        { name: "The Hawk 101.5", city: "Halifax", genre: "Classic Rock", url: "http://thehawk.streamon.fm:8000/CIGO-48k.aac" },
        { name: "Première Chaîne", city: "Montreal", genre: "French Talk", url: "http://cbc_r1_mtl.akacast.akamaistream.net/7/949/451661/v1/rc.akacast.akamaistream.net/cbc_r1_mtl" },
        { name: "Ici Musique", city: "Montreal", genre: "French Eclectic", url: "http://cbc_r2_mtl.akacast.akamaistream.net/7/92/451661/v1/rc.akacast.akamaistream.net/cbc_r2_mtl" },
        { name: "CFOX 99.3", city: "Vancouver", genre: "Rock", url: "https://cfox.streamon.fm/CFOX-48k.aac" },
        { name: "KiSS 92.5", city: "Toronto", genre: "Top 40", url: "https://rogers-hls.leanstream.co/rogers/tor925.stream/playlist.m3u8" },
        { name: "Q107", city: "Toronto", genre: "Classic Rock", url: "https://q107.streamon.fm/CILQ-48k.aac" },
        { name: "Fresh 103.1", city: "London, ON", genre: "Hot AC", url: "https://freshfm.streamon.fm:8000/CKFM-48k.aac" },
        { name: "CFMU 93.3", city: "Hamilton", genre: "Campus Radio", url: "https://s4.radio.co/s2b2b64444/listen" },
        { name: "CITR 101.9", city: "Vancouver", genre: "Campus Radio", url: "http://live.citr.ca:8000/live.mp3" }
    ],
    "France": [
        { name: "FIP", city: "Paris", genre: "Eclectic", url: "http://icecast.radiofrance.fr/fip-hifi.mp3" },
        { name: "France Inter", city: "Paris", genre: "News/Talk", url: "http://icecast.radiofrance.fr/franceinter-hifi.mp3" },
        { name: "France Musique", city: "Paris", genre: "Classical/Jazz", url: "http://icecast.radiofrance.fr/francemusique-hifi.mp3" },
        { name: "France Culture", city: "Paris", genre: "Culture/Talk", url: "http://icecast.radiofrance.fr/franceculture-hifi.mp3" },
        { name: "RFI Monde", city: "Paris", genre: "World News", url: "http://live.rfi.fr/wor/en/pub/out/mp3/128/stream.mp3" },
        { name: "Radio Nova", city: "Paris", genre: "World/Electronic", url: "http://novazz.ice.infomaniak.ch/novazz-128.mp3" },
        { name: "Nostalgie", city: "Paris", genre: "80s/90s Hits", url: "http://185.52.127.132/fr/30601/mp3_128.mp3?origine=fluxradios" },
        { name: "NRJ", city: "Paris", genre: "Top 40", url: "http://185.52.127.132/fr/30001/mp3_128.mp3" },
        { name: "Radio Classique", city: "Paris", genre: "Classical", url: "http://radioclassique.ice.infomaniak.ch/radioclassique-high.mp3" },
        { name: "TSF Jazz", city: "Paris", genre: "Jazz", url: "http://tsfjazz.ice.infomaniak.ch/tsfjazz-high.mp3" },
        { name: "Le Mouv'", city: "Paris", genre: "Youth/Alternative", url: "http://icecast.radiofrance.fr/mouv-hifi.mp3" },
        { name: "Latina", city: "Paris", genre: "Latin", url: "http://start-latina.ice.infomaniak.ch/start-latina-high.mp3" },
        { name: "Radio Meuh", city: "Reblochon", genre: "Eclectic", url: "http://radiomeuh.ice.infomaniak.ch/radiomeuh-128.mp3" },
        { name: "Chante France", city: "Paris", genre: "French Pop", url: "http://stream.chantef.fr/chantefrance.mp3" },
        { name: "FG Chic", city: "Paris", genre: "Lounge/Chillout", url: "http://radiofg.impek.com/fg_chic" },
        { name: "Fun Radio", city: "Paris", genre: "Dance", url: "http://streaming.radio.funradio.fr/fun-1-44-128" },
        { name: "RTL", city: "Paris", genre: "General", url: "http://streaming.radio.rtl.fr/rtl-1-44-128" },
        { name: "Europe 1", city: "Paris", genre: "General", url: "http://ais-live.cloud-services.paris:8000/europe1.mp3" },
        { name: "BFM Business", city: "Paris", genre: "Business News", url: "http://audio.bfmtv.com/bfmbusiness_128.mp3" },
        { name: "Rire et Chansons", city: "Paris", genre: "Comedy/Pop", url: "http://185.52.127.132/fr/30401/mp3_128.mp3" }
    ],
    "Germany": [
        { name: "Deutschlandfunk", city: "Cologne", genre: "News/Talk", url: "https://st01.dlf.de/dlf/01/128/mp3/stream.mp3" },
        { name: "FluxFM", city: "Berlin", genre: "Alternative", url: "http://stream.fluxfm.de/fluxfm-berlin/mp3-128/streams.fluxfm.de/" },
        { name: "Radio BOB!", city: "Kassel", genre: "Rock", url: "http://streams.radiobob.de/bob-live/mp3-192/mediaplayer" },
        { name: "Antenne Bayern", city: "Ismaning", genre: "Pop", url: "http://mp3channels.webradio.antenne.de/antenne" },
        { name: "JazzRadio", city: "Berlin", genre: "Jazz", url: "http://www.jazzradio.net/stream" },
        { name: "Klassik Radio", city: "Hamburg", genre: "Classical", url: "http://streams.klassikradio.de/live/mp3-128/stream.klassikradio.de" },
        { name: "ByteFM", city: "Hamburg", genre: "Indie", url: "https://stream.byte.fm/bytefm-128.mp3" },
        { name: "EgoFM", city: "Munich", genre: "Indie/Alternative", url: "http://stream.egofm.de/egofm/mp3-128/vtuner/" },
        { name: "Radio Fritz", city: "Potsdam", genre: "Youth", url: "http://rbb-fritz-live.cast.addradio.de/rbb/fritz/live/mp3/128/stream.mp3" },
        { name: "Sunshine Live", city: "Mannheim", genre: "Techno", url: "http://stream.sunshine-live.de/live/mp3-128/sunshinelive" },
        { name: "Radioeins", city: "Potsdam", genre: "Public/Eclectic", url: "http://rbb-radioeins-live.cast.addradio.de/rbb/radioeins/live/mp3/128/stream.mp3" },
        { name: "WDR 5", city: "Cologne", genre: "Talk/Documentary", url: "http://wdr-wdr5-live.icecast.wdr.de/wdr/wdr5/live/mp3/128/stream.mp3" },
        { name: "Cosmo", city: "Cologne", genre: "World Music", url: "http://wdr-cosmo-live.icecast.wdr.de/wdr/cosmo/live/mp3/128/stream.mp3" },
        { name: "Rock Antenne", city: "Ismaning", genre: "Classic Rock", url: "http://mp3.webradio.rockantenne.de/rockantenne" },
        { name: "Delta Radio", city: "Kiel", genre: "Alternative", url: "http://streams.deltaradio.de/delta-live/mp3-192/mediaplayer-playlist/" },
        { name: "Radio Hamburg", city: "Hamburg", genre: "Top 40", url: "https://stream.radiohamburg.de/rhh-live/mp3-192/listenlive" },
        { name: "NDR 2", city: "Hamburg", genre: "Pop", url: "http://icecast.ndr.de/ndr/ndr2/niedersachsen/mp3/128/stream.mp3" },
        { name: "BLN.FM", city: "Berlin", genre: "Electronic", url: "https://bln.fm/stream/" },
        { name: "80s80s", city: "National", genre: "80s Pop", url: "http://streams.80s80s.de/web/mp3-192" },
        { name: "Absolut Relax", city: "National", genre: "Soft Pop/Chill", url: "https://absolutradio.de/playlist/absolut-relax.m3u" }
    ],
    "India": [
        { name: "Radio City Hindi", city: "Mumbai", genre: "Bollywood", url: "https://prclive1.listenon.in/Hindi" },
        { name: "Radio Mirchi 98.3", city: "Mumbai", genre: "Bollywood", url: "http://peridot.streamguys.com:7150/Mirchi" },
        { name: "All India Radio", city: "Delhi", genre: "News/Talk", url: "http://air.pc.cdn.bitgravity.com/air/live/pbaudio001/playlist.m3u8" },
        { name: "Ishq FM", city: "Delhi", genre: "Romantic", url: "https://playerservices.streamtheworld.com/api/livestream-redirect/ISHQ_DEL.mp3" },
        { name: "Radio Mango", city: "Kochi", genre: "Malayalam", url: "https://str.radiomango.fm/mangolive/radiomango/playlist.m3u8" },
        { name: "Fever FM", city: "Delhi", genre: "Bollywood", url: "https://stream.fever.fm/delhi-128" },
        { name: "Radio Indigo", city: "Bangalore", genre: "English Hits", url: "https://stream.radioindigo.fm/indigo-128" },
        { name: "My FM", city: "Jaipur", genre: "Bollywood", url: "https://prclive1.listenon.in/myfm" },
        { name: "Radio One", city: "Delhi", genre: "Bollywood", url: "https://playerservices.streamtheworld.com/api/livestream-redirect/RADIOONE_DEL.mp3" },
        { name: "Radio Sharda", city: "Jammu", genre: "Kashmiri", url: "http://198.178.121.76:8145/stream" },
        { name: "Suryan FM", city: "Chennai", genre: "Tamil", url: "http://suryanfm.in:8000/suryanfm-128" },
        { name: "Radio Aamar", city: "Kolkata", genre: "Bengali", url: "http://103.16.47.70:7070/;" },
        { name: "Luminous Radio", city: "Online", genre: "Christian", url: "https://luminousradio.com/listen" },
        { name: "Radio Afsana", city: "Online", genre: "Hindi", url: "https://radioafsana.com:8443/stream" },
        { name: "Radio Dhaakad", city: "Haryana", genre: "Haryanvi", url: "https://node-14.zeno.fm/fnf2x2q6p2zuv" },
        { name: "Radio Badal", city: "Shimla", genre: "Himachali", url: "https://node-24.zeno.fm/e2g5y61a1h0uv" },
        { name: "Club FM", city: "Dubai", genre: "Malayalam", url: "https://d2q23vdf4wezpa.cloudfront.net/out/v1/70817c703b44422e84126c04f44777b7/index.m3u8" },
        { name: "Radio Gurbani", city: "Online", genre: "Sikh Devotional", url: "https://s2.radio.co/s83777f37b/listen" },
        { name: "The Movement", city: "Online", genre: "Hip Hop", url: "https://themovement.in/radio/8000/radio.mp3" },
        { name: "Boxout.fm", city: "Delhi", genre: "Electronic/Indie", url: "https://stream.boxout.fm/listen" }
    ],
    "Ireland": [
        { name: "RTÉ Radio 1", city: "Dublin", genre: "News/Talk", url: "http://icecast1.rte.ie/radio1" },
        { name: "RTÉ 2FM", city: "Dublin", genre: "Pop", url: "http://icecast1.rte.ie/2fm" },
        { name: "Today FM", city: "Dublin", genre: "Pop/Talk", url: "https://media-ice.musicradio.com/TodayFM" },
        { name: "Newstalk", city: "Dublin", genre: "News/Talk", url: "https://media-ice.musicradio.com/Newstalk" },
        { name: "RTÉ Lyric FM", city: "Limerick", genre: "Classical/Arts", url: "http://icecast1.rte.ie/lyric" },
        { name: "SPIN 1038", city: "Dublin", genre: "Top 40", url: "https://media-ice.musicradio.com/SPIN1038" },
        { name: "Classic Hits", city: "Dublin", genre: "80s/90s", url: "https://media-ice.musicradio.com/ClassicHits" },
        { name: "98FM", city: "Dublin", genre: "Pop", url: "https://media-ice.musicradio.com/98FM" },
        { name: "Dublin's Q102", city: "Dublin", genre: "Adult Contemporary", url: "https://media-ice.musicradio.com/Q102" },
        { name: "Raidió na Gaeltachta", city: "Galway", genre: "Irish Language", url: "http://icecast1.rte.ie/rnag" },
        { name: "Red FM", city: "Cork", genre: "Pop", url: "https://media-ice.musicradio.com/RedFM" },
        { name: "Galway Bay FM", city: "Galway", genre: "Local", url: "http://streams.galwaybayfm.ie:8000/;" },
        { name: "Radio Nova", city: "Dublin", genre: "Classic Rock", url: "http://ice.radionova.ie/nova" },
        { name: "8Radio", city: "Dublin", genre: "Alternative", url: "https://listen.8radio.com/8radio.mp3" },
        { name: "iRadio", city: "Athlone", genre: "Top 40", url: "https://stream.iradio.ie/iradio.mp3" },
        { name: "Sunshine 106.8", city: "Dublin", genre: "Easy Listening", url: "http://stream.sunshineradio.ie/sunshine.mp3" },
        { name: "FM104", city: "Dublin", genre: "Pop", url: "https://media-ice.musicradio.com/FM104" },
        { name: "LMFM", city: "Drogheda", genre: "Local", url: "https://live.sharp-stream.com/lmfm.mp3" },
        { name: "Radio Kerry", city: "Tralee", genre: "Local", url: "https://kerry.icy.stream/kerry.mp3" },
        { name: "Clare FM", city: "Ennis", genre: "Local", url: "https://stream.clare.fm/clarefm.mp3" }
    ],
    "Italy": [
        { name: "RAI Radio 1", city: "Rome", genre: "News/Talk", url: "http://icestreaming.rai.it/1.mp3" },
        { name: "RAI Radio 2", city: "Rome", genre: "Pop/Talk", url: "http://icestreaming.rai.it/2.mp3" },
        { name: "RAI Radio 3", city: "Rome", genre: "Classical/Culture", url: "http://icestreaming.rai.it/3.mp3" },
        { name: "Radio Deejay", city: "Milan", genre: "Pop", url: "http://radiodeejay-lh.akamaihd.net/i/RadioDeejay_Live_1@189857/master.m3u8" },
        { name: "Radio 105", city: "Milan", genre: "Top 40", url: "http://icecast.105.net/105.mp3" },
        { name: "Virgin Radio", city: "Milan", genre: "Rock", url: "http://icecast.unitedradio.it/Virgin.mp3" },
        { name: "R101", city: "Milan", genre: "Pop", url: "http://icecast.unitedradio.it/r101.mp3" },
        { name: "Radio Monte Carlo", city: "Milan", genre: "Lounge/Pop", url: "http://edge.singsingmusic.net/rmc.mp3" },
        { name: "RDS", city: "Rome", genre: "Pop", url: "https://stream.rds.radio/rds/mp3-128" },
        { name: "Radio Capital", city: "Rome", genre: "Classic Hits/Soul", url: "http://radiocapital-lh.akamaihd.net/i/RadioCapital_Live_1@196312/master.m3u8" },
        { name: "m2o", city: "Rome", genre: "Dance", url: "http://radiom2o-lh.akamaihd.net/i/RadioM2o_Live_1@189858/master.m3u8" },
        { name: "Radio Kiss Kiss", city: "Naples", genre: "Pop", url: "http://kiskis.ice.infomaniak.ch/kiskis-128.mp3" },
        { name: "Radiofreccia", city: "Milan", genre: "Rock", url: "https://streamingv2.shoutcast.com/radiofreccia" },
        { name: "Radio 24", city: "Milan", genre: "News/Talk", url: "http://shoutcast.radio24.it:8000/;" },
        { name: "Radio Subasio", city: "Assisi", genre: "Italian Pop", url: "http://onair18.xdevel.com:8002/;" },
        { name: "Discoradio", city: "Milan", genre: "Dance/Pop", url: "http://icecast.discoradio.it:8000/discoradio.mp3" },
        { name: "Radio Sportiva", city: "Prato", genre: "Sports", url: "http://onair18.xdevel.com:8032/;" },
        { name: "Radio Popolare", city: "Milan", genre: "Independent/Talk", url: "https://www.radiopopolare.it/streaming/radiopopolare.mp3" },
        { name: "Lifegate Radio", city: "Milan", genre: "New Age/Chillout", url: "https://stream.lifegate.it/lifegate_radio.mp3" },
        { name: "Radio Radicale", city: "Rome", genre: "Political/Talk", url: "https://stream.radioradicale.it/radioradicale_1-128.mp3" }
    ],
    "Japan": [
        { name: "Asia Dream Radio", city: "Nagoya", genre: "J-Pop", url: "http://listen.asiadreamradio.com:8000/hi" },
        { name: "Vocaloid Radio", city: "Online", genre: "Vocaloid", url: "http://curiosity.shoutca.st:8019/stream" },
        { name: "AFN Tokyo", city: "Tokyo", genre: "US Military", url: "http://202.218.219.100:8000/stream.mp3" },
        { name: "Japan Hits", city: "Online", genre: "J-Pop", url: "http://listen.181fm.com/181-jpop_128k.mp3" },
        { name: "AnimeNfo", city: "Online", genre: "Anime", url: "http://animeradio.su:8000/stream" },
        { name: "FM Karuizawa", city: "Karuizawa", genre: "Community", url: "http://fm-karuizawa.co.jp/simul-radio.htm" },
        { name: "Radio Kishiwada", city: "Osaka", genre: "Community", url: "http://www.radiokishiwada.jp/simul/" },
        { name: "Kyoto Sanjo", city: "Kyoto", genre: "Community", url: "http://radiocafe.jp/simul/" },
        { "name": "J-Rock Powerplay", "city": "Online", "genre": "J-Rock", "url": "http://178.32.137.195:8167/stream" },
        { "name": "J-Pop Powerplay", "city": "Online", "genre": "J-Pop", "url": "http://178.32.137.195:8130/stream" },
        { "name": "FM Nishi-Tokyo", "city": "Tokyo", "genre": "Community", "url": "http://s3.radio.co/s3e41b65e9/listen" },
        { "name": "FM SETO", "city": "Seto", "genre": "Community", "url": "http://s2.radio.co/s2f9b841e2/listen" },
        { "name": "FM Hirakata", "city": "Osaka", "genre": "Community", "url": "https://s3.radio.co/s57c2c5e53/listen" },
        { "name": "FM Odawara", "city": "Odawara", "genre": "Community", "url": "http://s2.radio.co/s3e015d9a9/listen" },
        { "name": "Kittikun Minimal Techno", "city": "Online", "genre": "Techno", "url": "http://192.99.8.192:2566/;" },
        { "name": "Banana FM", "city": "Wakayama", "genre": "Community", "url": "http://s4.radio.co/s2b2b64444/listen" },
        { "name": "FM Nanami", "city": "Aichi", "genre": "Community", "url": "http://s2.radio.co/s4c935414d/listen" },
        { "name": "Momo-Lala", "city": "Online", "genre": "Classical", "url": "http://192.99.8.192:5694/stream" },
        { "name": "Radio Hayama", "city": "Hayama", "genre": "Community", "url": "http://s3.radio.co/s215b28a9b/listen" },
        { "name": "Retro PC Game Music", "city": "Online", "genre": "Video Game Music", "url": "http://172.93.103.11:8060/stream" }
    ],
    "Mexico": [
        { name: "W Radio", city: "Mexico City", genre: "News/Talk", url: "http://14933.live.streamtheworld.com:3690/XEW_AM_SC" },
        { name: "Los 40 México", city: "Mexico City", genre: "Top 40", url: "https://14083.live.streamtheworld.com/LOS40_MEXICO_SC" },
        { name: "Exa FM", city: "Mexico City", genre: "Pop", url: "https://playerservices.streamtheworld.com/api/livestream-redirect/XHEXA_FM.mp3" },
        { name: "Amor 95.3", city: "Mexico City", genre: "Romantic", url: "https://playerservices.streamtheworld.com/api/livestream-redirect/XHSH_FM.mp3" },
        { name: "La Z 107.3 FM", city: "Mexico City", genre: "Regional Mexican", url: "http://playerservices.streamtheworld.com/api/livestream-redirect/XEQR_FM.mp3" },
        { name: "Reactor 105.7", city: "Mexico City", genre: "Rock/Alternative", url: "https://s2.mexside.net:8026/stream" },
        { name: "Ibero 90.9", city: "Mexico City", genre: "College/Indie", url: "https://ibero909.fm:8443/ibero.mp3" },
        { name: "Opus 94", city: "Mexico City", genre: "Classical", url: "https://s2.mexside.net:8024/stream" },
        { name: "Radio Fórmula", city: "Mexico City", genre: "News/Talk", url: "http://ice55.securenetsystems.net/XERFR" },
        { name: "Alfa 91.3", city: "Mexico City", genre: "Top 40", url: "http://playerservices.streamtheworld.com/api/livestream-redirect/XHFAJ_FM.mp3" },
        { name: "Universal Stereo", city: "Mexico City", genre: "Classic Hits", url: "http://playerservices.streamtheworld.com/api/livestream-redirect/XHMVS_FM.mp3" },
        { name: "La Mejor FM", city: "Mexico City", genre: "Grupero", url: "http://playerservices.streamtheworld.com/api/livestream-redirect/XEQ_FM.mp3" },
        { name: "Oye 89.7", city: "Mexico City", genre: "Pop", url: "https://playerservices.streamtheworld.com/api/livestream-redirect/XEOYE_FM.mp3" },
        { name: "Ke Buena", city: "Mexico City", genre: "Regional Mexican", url: "https://17453.live.streamtheworld.com/XEQ_FM_SC" },
        { name: "Horizonte 107.9", city: "Mexico City", genre: "Jazz", url: "https://s2.mexside.net:8022/stream" },
        { name: "MVS Noticias", city: "Mexico City", genre: "News", url: "http://playerservices.streamtheworld.com/api/livestream-redirect/XHMVS_FM.mp3" },
        { name: "Sabrosita 590 AM", city: "Mexico City", genre: "Tropical/Salsa", url: "http://playerservices.streamtheworld.com/api/livestream-redirect/XEPH_AM.mp3" },
        { name: "Radio Disney", city: "Mexico City", genre: "Pop", url: "https://playerservices.streamtheworld.com/api/livestream-redirect/XHRCA_FM.mp3" },
        { name: "El Fonógrafo", city: "Mexico City", genre: "Oldies (Spanish)", url: "http://14933.live.streamtheworld.com/XEJP_AM_SC" },
        { name: "Radio UNAM", city: "Mexico City", genre: "University/Culture", url: "http://132.248.11.11:8000/;" }
    ],
    "Netherlands": [
        { name: "NPO Radio 1", city: "Hilversum", genre: "News/Talk", url: "http://icecast.omroep.nl/radio1-bb-mp3" },
        { name: "NPO Radio 2", city: "Hilversum", genre: "Pop/Rock", url: "http://icecast.omroep.nl/radio2-bb-mp3" },
        { name: "NPO 3FM", city: "Hilversum", genre: "Alternative", url: "http://icecast.omroep.nl/3fm-bb-mp3" },
        { name: "NPO Radio 4", city: "Hilversum", genre: "Classical", url: "http://icecast.omroep.nl/radio4-bb-mp3" },
        { name: "Radio 538", city: "Hilversum", genre: "Top 40", url: "https://playerservices.streamtheworld.com/api/livestream-redirect/RADIO538.mp3" },
        { name: "Qmusic", city: "Amsterdam", genre: "Pop", url: "https://icecast-qmusicnl-cdp.triple-it.nl/Qmusic_nl_live_96.mp3" },
        { name: "Sky Radio", city: "Hilversum", genre: "Pop/Easy Listening", url: "https://playerservices.streamtheworld.com/api/livestream-redirect/SKYRADIO.mp3" },
        { name: "Radio 10", city: "Hilversum", genre: "Classic Hits", url: "https://playerservices.streamtheworld.com/api/livestream-redirect/RADIO10.mp3" },
        { name: "Veronica", city: "Hilversum", genre: "Rock", url: "https://playerservices.streamtheworld.com/api/livestream-redirect/VERONICA.mp3" },
        { name: "KINK", city: "Hilversum", genre: "Alternative/Rock", url: "https://playerservices.streamtheworld.com/api/livestream-redirect/KINK.mp3" },
        { name: "BNR Nieuwsradio", city: "Amsterdam", genre: "Business News", url: "http://icecast-fdg.cdp.triple-it.nl/bnr_mp3_96_01" },
        { name: "Sublime", city: "Utrecht", genre: "Jazz/Soul", url: "https://playerservices.streamtheworld.com/api/livestream-redirect/SUBLIME.mp3" },
        { name: "Slam!", city: "Hilversum", genre: "Dance", url: "https://playerservices.streamtheworld.com/api/livestream-redirect/SLAMFM.mp3" },
        { name: "FunX", city: "Amsterdam", genre: "Urban", url: "http://icecast.omroep.nl/funx-bb-mp3" },
        { name: "Pinguin Radio", city: "Online", genre: "Indie", url: "http://pr320.pinguinradio.com/listen.mp3" },
        { name: "Concertzender", city: "Utrecht", genre: "Classical/Jazz", url: "https://streams.greenhost.nl:8000/concertzender.ogg" },
        { name: "Arrow Classic Rock", city: "Rijswijk", genre: "Classic Rock", url: "http://stream.arrow.nl/arrow" },
        { name: "Radio Decibel", city: "Amsterdam", genre: "90s Hits", url: "https://stream.decibel.nl/decibel.mp3" },
        { name: "Groot Nieuws Radio", city: "Veenendaal", genre: "Christian", url: "http://stream.hoerradar.de/gnr-mp3-128" },
        { name: "Soulshow Radio", city: "Online", genre: "Soul/Funk", url: "https://stream.soulshow.nl/soulshow-128" }
    ],
    "New Zealand": [
        { name: "RNZ National", city: "Wellington", genre: "News/Talk", url: "https://radionz-ice.streamguys.com/national.mp3" },
        { name: "RNZ Concert", city: "Wellington", genre: "Classical", url: "https://radionz-ice.streamguys.com/concert.mp3" },
        { name: "The Edge", city: "Auckland", genre: "Top 40", url: "https://ais-nz.streamguys1.com/nz-theedge/ice-128" },
        { name: "The Rock", city: "Auckland", genre: "Rock", url: "https://ais-nz.streamguys1.com/nz-therock/ice-128" },
        { name: "ZM", city: "Auckland", genre: "Top 40", url: "https://ais-nz.streamguys1.com/nz-zm/ice-128" },
        { name: "Newstalk ZB", city: "Auckland", genre: "News/Talk", url: "https://ais-nz.streamguys1.com/nz-newstalkzb/ice-128" },
        { name: "The Sound", city: "Auckland", genre: "Classic Rock", url: "https://ais-nz.streamguys1.com/nz-thesound/ice-128" },
        { name: "More FM", city: "Auckland", genre: "Adult Contemporary", url: "https://ais-nz.streamguys1.com/nz-morefm/ice-128" },
        { name: "Radio Hauraki", city: "Auckland", genre: "Alternative Rock", url: "https://ais-nz.streamguys1.com/nz-hauraki/ice-128" },
        { name: "95bFM", city: "Auckland", genre: "Student Radio", url: "http://streams.95bfm.com/stream" },
        { name: "George FM", city: "Auckland", genre: "Dance/Electronic", url: "https://ais-nz.streamguys1.com/nz-georgefm/ice-128" },
        { name: "The Breeze", city: "Auckland", genre: "Easy Listening", url: "https://ais-nz.streamguys1.com/nz-thebreeze/ice-128" },
        { name: "Radio Active 88.6FM", city: "Wellington", genre: "Independent", url: "http://stream.radioactive.fm:8000/ractive" },
        { name: "The Most FM", city: "Taranaki", genre: "Community", url: "https://streaming.planetwideradio.com/proxy/themost?mp=/stream" },
        { name: "Base FM", city: "Auckland", genre: "Hip Hop/Soul", url: "https://s3.radio.co/s3e6b542e7/listen" },
        { name: "Coast", city: "Auckland", genre: "Classic Hits", url: "https://ais-nz.streamguys1.com/nz-coast/ice-128" },
        { name: "Radio Spice", city: "Auckland", genre: "Indian", url: "http://167.114.64.181:8167/stream/;" },
        { name: "Life FM", city: "Auckland", genre: "Christian", url: "https://stream.rhema.co.nz/lifefm" },
        { name: "Pulzar FM", city: "Christchurch", genre: "Dance", url: "https://streams.pulzarfm.co.nz/pulzar128" },
        { name: "Magic", city: "Auckland", genre: "Oldies", url: "https://ais-nz.streamguys1.com/nz-magic/ice-128" }
    ],
    "Nigeria": [
        { name: "Cool FM 96.9", city: "Lagos", genre: "Top 40", url: "https://coolfm-lagos.stream.ng/http" },
        { name: "Wazobia FM 95.1", city: "Lagos", genre: "Pidgin English/Pop", url: "https://wazobiafm-lagos.stream.ng/http" },
        { name: "The Beat 99.9 FM", city: "Lagos", genre: "Urban", url: "https://thebeat99.stream.ng/http" },
        { name: "Nigeria Info 99.3", city: "Lagos", genre: "News/Talk", url: "https://nigeriainfo-lagos.stream.ng/http" },
        { name: "Classic FM 97.3", city: "Lagos", genre: "Oldies", url: "https://classicfm-lagos.stream.ng/http" },
        { name: "Soundcity 98.5 FM", city: "Lagos", genre: "Afrobeats", url: "http://192.240.102.133:10950/stream" },
        { name: "Inspiration FM 92.3", city: "Lagos", genre: "Family/Gospel", url: "http://192.240.102.133:10962/stream" },
        { name: "Smooth 98.1", city: "Lagos", genre: "Jazz/Soul", url: "https://stream.smooth981.fm/smooth981" },
        { name: "Freedom Radio", city: "Kano", genre: "Hausa", url: "http://192.240.102.133:11110/stream" },
        { name: "Splash FM 105.5", city: "Ibadan", genre: "General", url: "http://192.240.102.133:10978/stream" },
        { name: "RFI Hausa", city: "Paris", genre: "News (Hausa)", url: "http://live.rfi.fr/ha/en/pub/out/mp3/128/stream.mp3" },
        { name: "Lagelu FM 96.7", city: "Ibadan", genre: "Yoruba", url: "http://192.240.102.133:10970/stream" },
        { name: "Urban 96.5 FM", city: "Lagos", genre: "Urban", url: "http://192.240.102.133:10966/stream" },
        { name: "Max 102.3 FM", city: "Lagos", genre: "Pop", url: "https://max1023.fm/listen-live" },
        { name: "City 105.1 FM", city: "Lagos", genre: "Lifestyle", url: "https://city1051fm.com/listen-live-2/" },
        { name: "Praise World Radio", city: "Lagos", genre: "Gospel", url: "http://192.240.102.133:10994/stream" },
        { name: "Gospotainment Radio", city: "Lagos", genre: "Gospel", url: "http://188.166.21.200:8012/stream" },
        { name: "Top Radio 90.9 FM", city: "Lagos", genre: "General", url: "http://192.240.102.133:10958/stream" },
        { name: "Hot FM 98.3", city: "Abuja", genre: "Top 40", url: "https://hotfm-abuja.stream.ng/http" },
        { name: "Afrobeat Radio", city: "Lagos", genre: "Afrobeats", url: "https://streaming.radionomy.com/AfrobeatRadio" }
    ],
    "South Korea": [
        { name: "KBS 1Radio", city: "Seoul", genre: "News/Talk", url: "https://onair.kbs.co.kr/index.html?sname=onair&stype=live&ch_code=21" },
        { name: "KBS Cool FM", city: "Seoul", genre: "K-Pop", url: "https://onair.kbs.co.kr/index.html?sname=onair&stype=live&ch_code=22" },
        { name: "MBC FM4U", city: "Seoul", genre: "Pop/K-Pop", url: "http://miniplay.imbc.com/AAC/GMFM4U.m3u8" },
        { name: "SBS Power FM", city: "Seoul", genre: "K-Pop", url: "http://m.sbs.co.kr/player/onair.do?channel=S08" },
        { name: "TBS eFM", city: "Seoul", genre: "English Talk/Music", url: "http://tbs.hscdn.com/efm/definst/efm.stream/playlist.m3u8" },
        { name: "Arirang Radio", city: "Seoul", genre: "English K-Pop", url: "http://arirangradio.cf.lnf.kr/arirang_radio/playlist.m3u8" },
        { name: "BBS FM", city: "Seoul", genre: "Buddhist", url: "http://mms.bbsfm.co.kr:8080/bbsfm_live" },
        { name: "CBS Music FM", city: "Seoul", genre: "Christian/Pop", url: "http://cbsmusic.live-smc.com/cbsmusic.sdp/playlist.m3u8" },
        { name: "YTN News FM", city: "Seoul", genre: "News", url: "https://service.ytn.co.kr/radio/live.m3u8" },
        { name: "Gugak FM", city: "Seoul", genre: "Traditional Korean", url: "http://mgugaklive.nowcdn.co.kr/gugakradio/gugakradio.stream/playlist.m3u8" },
        { name: "K-Pop Addict", city: "Online", genre: "K-Pop", url: "http://stream.zeno.fm/g69zsuw3p2zuv" },
        { name: "Big B Radio (KPop)", city: "Online", genre: "K-Pop", url: "http://streams.bigbradio.net/kpop" },
        { name: "Jazzheart Radio", city: "Online", genre: "Jazz", url: "http://stream.jazzheart.co.kr:8000/;" },
        { name: "Aewen Radio", city: "Online", genre: "K-Pop/J-Pop", url: "https://aewen.com:8000/listen" },
        { name: "K-Popway", city: "Online", genre: "K-Pop", url: "https://stream.kpopway.com/kpopway.mp3" },
        { name: "Mapo FM", city: "Seoul", genre: "Community", url: "http://mapofm.net:8000/mapofm" },
        { name: "GFN", city: "Gwangju", genre: "English Radio", url: "http://210.94.205.105:1935/live/gfn.stream/playlist.m3u8" },
        { name: "BFN", city: "Busan", genre: "English Radio", url: "http://str.befm.or.kr:1935/live/befm.stream/playlist.m3u8" },
        { name: "FEBC", city: "Seoul", genre: "Christian", url: "http://211.233.34.40:1935/live/ch1.stream/playlist.m3u8" },
        { name: "WBS", city: "Seoul", genre: "Original Sound", url: "http://118.67.133.45/live/wbs.sdp/playlist.m3u8" }
    ],
    "Spain": [
        { name: "Cadena SER", city: "Madrid", genre: "News/Talk", url: "http://195.55.74.205/cadenaser/SER_Madrid.mp3" },
        { name: "Los 40", city: "Madrid", genre: "Top 40", url: "http://195.55.74.205/los40/los40_Madrid.mp3" },
        { name: "Cadena 100", city: "Madrid", genre: "Pop", url: "https://cadena100-cope-rrcast.flumotion.com/cope/cadena100-low.mp3" },
        { name: "Rock FM", city: "Madrid", genre: "Rock", url: "https://rockfm-cope-rrcast.flumotion.com/cope/rockfm-low.mp3" },
        { name: "Radio 3", city: "Madrid", genre: "Alternative", url: "http://rtve-live.hls.adaptive.level3.net/hls-live/rtve-radio3/_definst_/livestream.m3u8" },
        { name: "Radio Clásica", city: "Madrid", genre: "Classical", url: "http://rtve-live.hls.adaptive.level3.net/hls-live/rtve-radioclasica/_definst_/livestream.m3u8" },
        { name: "Flaix FM", city: "Barcelona", genre: "Dance", url: "https://streaming.flaixfm.cat/flaixfm.mp3" },
        { name: "RAC1", city: "Barcelona", genre: "Talk (Catalan)", url: "https://streaming.rac1.cat/rac1.mp3" },
        { name: "Catalunya Ràdio", city: "Barcelona", genre: "Talk (Catalan)", url: "https://shoutcast.ccma.cat/ccma/catalunyaradio-aac" },
        { name: "Radio Marca", city: "Madrid", genre: "Sports", url: "https://playerservices.streamtheworld.com/api/livestream-redirect/RADIOMARCA.mp3" },
        { name: "Europa FM", city: "Madrid", genre: "Pop", url: "https://atresmedia-radio.stream.flumotion.com/atresmedia/europafm-mp3" },
        { name: "Kiss FM", city: "Madrid", genre: "80s/90s", url: "https://playerservices.streamtheworld.com/api/livestream-redirect/KISS_FM.mp3" },
        { name: "Melodía FM", city: "Madrid", genre: "Classic Hits", url: "https://atresmedia-radio.stream.flumotion.com/atresmedia/melodiafm-mp3" },
        { name: "Onda Cero", city: "Madrid", genre: "News/Talk", url: "https://atresmedia-radio.stream.flumotion.com/atresmedia/ondacero-mp3" },
        { name: "COPE", city: "Madrid", genre: "News/Talk", url: "https://cope-cope-rrcast.flumotion.com/cope/cope-low.mp3" },
        { name: "Ibiza Sonica Radio", city: "Ibiza", genre: "Electronic", url: "http://192.99.8.192:3132/stream" },
        { name: "Radio Chanquete FM", city: "Malaga", genre: "Flamenco", url: "http://195.154.49.200:8014/;" },
        { name: "Canal Fiesta Radio", city: "Seville", genre: "Spanish Pop", url: "http://www.canalsur.es/resources/TELETIPO/audio/2016/10/24/1477317370845fiesta_h.m3u" },
        { name: "Vaughan Radio", city: "Madrid", genre: "English Learning", url: "https://vaughanradio.streaming-pro.com:8010/vaughan-radio.mp3" },
        { name: "Radiolé", city: "Madrid", genre: "Spanish Pop", url: "http://195.55.74.205/radioser/RadiOle_Madrid.mp3" }
    ],
    "Sweden": [
        { name: "Sveriges Radio P1", city: "Stockholm", genre: "News/Talk", url: "https://sverigesradio.se/topsy/direkt/132-hi-mp3" },
        { name: "Sveriges Radio P2", city: "Stockholm", genre: "Classical/Jazz", url: "https://sverigesradio.se/topsy/direkt/2562-hi-mp3" },
        { name: "Sveriges Radio P3", city: "Stockholm", genre: "Pop/Alternative", url: "https://sverigesradio.se/topsy/direkt/164-hi-mp3" },
        { name: "Sveriges Radio P4", city: "Stockholm", genre: "Local/Pop", url: "https://sverigesradio.se/topsy/direkt/202-hi-mp3" },
        { name: "Rix FM", city: "Stockholm", genre: "Top 40", url: "https://live-bauerse-fm.sharp-stream.com/rix_fm_mp3" },
        { name: "NRJ Sweden", city: "Stockholm", genre: "Pop/Dance", url: "https://live-bauerse-fm.sharp-stream.com/nrj_sweden_mp3" },
        { name: "Bandit Rock", city: "Stockholm", genre: "Rock", url: "https://live-bauerse-fm.sharp-stream.com/bandit_rock_mp3" },
        { name: "Lugna Favoriter", city: "Stockholm", genre: "Soft Pop", url: "https://live-bauerse-fm.sharp-stream.com/lugna_favoriter_mp3" },
        { name: "Star FM", city: "Stockholm", genre: "80s/90s", url: "https://live-bauerse-fm.sharp-stream.com/star_fm_mp3" },
        { name: "Dansbandskanalen", city: "Online", genre: "Dansband", url: "http://radioplay.se/dbk.mp3" },
        { name: "Vinyl FM", city: "Stockholm", genre: "60s/70s", url: "https://live-bauerse-fm.sharp-stream.com/vinyl_fm_mp3" },
        { name: "Mix Megapol", city: "Stockholm", genre: "Adult Contemporary", url: "https://live-bauerse-fm.sharp-stream.com/mix_megapol_mp3" },
        { name: "Guldkanalen", city: "Kalmar", genre: "Classic Hits", url: "http://stream.dbmedia.se/gk128" },
        { name: "Rockklassiker", city: "Stockholm", genre: "Classic Rock", url: "https://live-bauerse-fm.sharp-stream.com/rockklassiker_mp3" },
        { name: "Radio Lidingö", city: "Lidingö", genre: "Community", url: "http://194.47.151.199:8000/listen.mp3" },
        { name: "Radio Sotenäs", city: "Sotenäs", genre: "Community", url: "http://194.71.185.122:8000/sotenas" },
        { name: "Radio Viking", city: "Ekerö", genre: "Community", url: "http://194.47.151.198:8000/listen.mp3" },
        { name: "SR Din Gata", city: "Malmö", genre: "Hip Hop/RnB", url: "https://sverigesradio.se/topsy/direkt/2576-hi-mp3" },
        { name: "Countrykanalen", city: "Stockholm", genre: "Country", url: "https://live-bauerse-fm.sharp-stream.com/country_classics_mp3" },
        { name: "Svensk Pop", city: "Stockholm", genre: "Swedish Pop", url: "https://live-bauerse-fm.sharp-stream.com/svensk_pop_mp3" }
    ],
    "United Kingdom": [
        { name: "BBC Radio 1", city: "London", genre: "Pop", url: "http://stream.live.vc.bbcmedia.co.uk/bbc_radio_one" },
        { name: "BBC Radio 2", city: "London", genre: "Adult Contemporary", url: "http://stream.live.vc.bbcmedia.co.uk/bbc_radio_two" },
        { name: "BBC Radio 3", city: "London", genre: "Classical", url: "http://stream.live.vc.bbcmedia.co.uk/bbc_radio_three" },
        { name: "BBC Radio 4", city: "London", genre: "News/Talk", url: "http://stream.live.vc.bbcmedia.co.uk/bbc_radio_fourfm" },
        { name: "BBC 6 Music", city: "London", genre: "Alternative", url: "http://stream.live.vc.bbcmedia.co.uk/bbc_6music" },
        { name: "Capital FM", city: "London", genre: "Top 40", url: "http://media-ice.musicradio.com/CapitalUKMP3" },
        { name: "Classic FM", city: "London", genre: "Classical", url: "http://media-ice.musicradio.com/ClassicFMMP3" },
        { name: "NTS Radio", city: "London", genre: "Underground", url: "http://stream-relay-geo.ntslive.net/stream" },
        { name: "Rinse FM", city: "London", genre: "Electronic/Grime", url: "http://streamer.rinse.fm/rinsefm.mp3" },
        { name: "LBC", city: "London", genre: "Talk", url: "http://media-ice.musicradio.com/LBCUKMP3" },
        { name: "Planet Rock", city: "London", genre: "Rock", url: "http://tx.planetradio.co.uk/icecast.php?i=planetrock.mp3" },
        { name: "Jazz FM", city: "London", genre: "Jazz", url: "http://tx.planetradio.co.uk/icecast.php?i=jazzfm.aac" },
        { name: "Scala Radio", city: "London", genre: "Modern Classical", url: "http://tx.planetradio.co.uk/icecast.php?i=scalaradio.aac" },
        { name: "Absolute Radio", city: "London", genre: "Rock", url: "http://ais.absoluteradio.co.uk/absoluteradio.mp3" },
        { name: "Kerrang! Radio", city: "London", genre: "Rock/Metal", url: "http://tx.planetradio.co.uk/icecast.php?i=kerrang.mp3" },
        { name: "Worldwide FM", city: "London", genre: "Eclectic", url: "https://worldwidefm.out.airtime.pro/worldwidefm_a" },
        { name: "Soho Radio", city: "London", genre: "Eclectic/Culture", url: "https://s2.radio.co/s5f2849591/listen" },
        { name: "Reprezent Radio", city: "London", genre: "Hip Hop/Electronic", url: "http://radio.reprezent.org.uk:8000/stream" },
        { name: "Subtle Radio", city: "London", genre: "Bass Music", url: "https://subtleradio.out.airtime.pro/subtleradio_a" },
        { name: "The Lot Radio", city: "New York/London", genre: "Underground Electronic", url: "https://thelot.out.airtime.pro/thelot_a" }
    ],
    "United States": [
        { name: "KCRW Eclectic24", city: "Santa Monica", genre: "Indie", url: "http://kcrw.streamguys1.com/kcrw_eclectic24_128k_mp3" },
        { name: "WNYC-FM", city: "New York", genre: "News/Talk", url: "http://fm939.wnyc.org/wnycfm" },
        { name: "KEXP 90.3 FM", city: "Seattle", genre: "Alternative", url: "http://live-mp3-128.kexp.org/" },
        { name: "Classical KUSC", city: "Los Angeles", genre: "Classical", url: "http://64.202.109.2:80/kusc128" },
        { name: "Jazz24", city: "Seattle", genre: "Jazz", url: "https://d.live.npr.org/streams/jazz24/jazz24/icecast.mp3" },
        { name: "Radio Paradise", city: "Global", genre: "Eclectic Rock", url: "http://stream.radioparadise.com/rock-128" },
        { name: "SomaFM: Groove Salad", city: "San Francisco", genre: "Ambient", url: "http://ice1.somafm.com/groovesalad-128-mp3" },
        { name: "WFMU", city: "Jersey City", genre: "Freeform", url: "http://stream.wfmu.org/freeform-128.mp3" },
        { name: "KPCC", city: "Pasadena", genre: "Public Radio", url: "http://live.scpr.org/kpcclive/" },
        { name: "The Current", city: "Minneapolis", genre: "Adult Alternative", url: "http://current.stream.publicradio.org/kcmp.mp3" },
        { name: "Dublab", city: "Los Angeles", genre: "Electronic", url: "http://dublab.out.airtime.pro:8000/dublab_128" },
        { name: "WWOZ 90.7 FM", city: "New Orleans", genre: "Jazz & Blues", url: "http://wwoz-sc.streamguys.com/wwoz-hi.mp3" },
        { name: "Radio Free Brooklyn", city: "Brooklyn", genre: "Community", url: "http://streaming.radio.co/s754e1a49a/listen" },
        { name: "KUTX 98.9", city: "Austin", genre: "AAA", url: "https://kutx.stream.publicradio.org/kutx.mp3" },
        { name: "Def Con Radio", city: "Las Vegas", genre: "Electronic/Talk", url: "http://ice1.somafm.com/defcon-128-mp3" },
        { name: "XRAY.fm", city: "Portland", genre: "Independent", url: "https://streaming.xray.fm/stream" },
        { name: "Gimme Radio", city: "San Francisco", genre: "Metal", url: "http://188.166.194.139:8000/gimmeradio" },
        { name: "Secret Agent from SomaFM", city: "San Francisco", genre: "Lounge", url: "http://ice1.somafm.com/secretagent-128-mp3" },
        { name: "Deep Space One", city: "Online", genre: "Space Ambient", url: "http://ice1.somafm.com/deepspaceone-128-mp3" },
        { name: "FIP", city: "Paris (USA Stream)", genre: "Eclectic", url: "http://icecast.radiofrance.fr/fip-hifi.mp3" }
    ]
};
